// Python async + sync client stub generator for the ProxyForge automation API.
import type { GeneratorInput } from './index';
import { OP_SCHEMAS } from './index';

export function generatePython(input: GeneratorInput): Array<{ filename: string; content: string }> {
  const baseUrl = input.baseUrl ?? 'http://127.0.0.1:8765';
  const ns = input.namespace ?? 'proxyforge';

  const methods = OP_SCHEMAS.map((op) => {
    const methodName = op.op.replace(/\./g, '_');
    const params = op.required.map((r) => `${r}: str`).join(', ');
    const paramsPassed = op.required.map((r) => `"${r}": ${r}`).join(', ');
    return `
  async def ${methodName}(self, ${params}) -> dict:
      """${op.description}"""
      return await self._send({"op": "${op.op}", ${paramsPassed}})`;
  }).join('\n');

  const content = `"""ProxyForge API client — auto-generated by ProxyForge apiGenerators.

Do not edit by hand; re-run the generator after updating the op schema.
"""
import json
import asyncio
from typing import Any
import urllib.request
import urllib.error


class ProxyForgeClient:
    """Async-compatible ProxyForge automation API client."""

    def __init__(self, base_url: str = "${baseUrl}", token: str | None = None):
        self._base_url = base_url.rstrip("/")
        self._token = token

    async def _send(self, payload: dict) -> dict:
        headers = {"Content-Type": "application/json"}
        if self._token:
            headers["Authorization"] = f"Bearer {self._token}"
        data = json.dumps(payload).encode()
        req = urllib.request.Request(f"{self._base_url}/rpc", data=data, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as e:
            return {"ok": False, "error": str(e)}
${methods}
`;

  return [{ filename: `${ns}_client.py`, content }];
}
