// Authoritative registry of all active scan check IDs.
// Each ID maps to a family file under src/scanner/families/.

export const ACTIVE_SCAN_CHECK_IDS = [
  // Core injection families
  'sql-injection',
  'xss-reflected',
  'xss-oracle',
  'ssti',
  'ssti-blind-time',
  'lfi-traversal',
  'command-injection',
  'command-injection-blind-time',
  'command-injection-blind-oast',
  'ssrf',
  'ssrf-oast',
  'open-redirect',
  'xxe-file',
  'xxe-oast',
  'nosql-injection',
  'xpath-injection',
  'ldap-injection',
  'expression-language-injection',
  'csv-formula-injection',
  // Auth / session
  'jwt-none-algorithm',
  'jwt-weak-secret',
  'jwt-key-confusion',
  'session-fixation',
  'csrf-heuristic',
  'clickjacking',
  'host-header-injection',
  'crlf-header-injection',
  'password-reset-token-leak',
  // Cache + smuggling
  'request-smuggling-cl-te',
  'request-smuggling-te-cl',
  'request-smuggling-te-te',
  'cache-poisoning-unkeyed-header',
  'cache-poisoning-unkeyed-port',
  'cache-deception',
  'web-cache-key-discrepancy',
  // Deserialization + blind RCE
  'deserialization-java',
  'deserialization-php',
  'deserialization-dotnet',
  'deserialization-python',
  'deserialization-ruby',
  // Client-side
  'dom-xss',
  'dom-clobbering',
  'prototype-pollution-client',
  'prototype-pollution-server',
  'postmessage-misconfig',
  'cors-misconfig-credentialed',
  // GraphQL + API
  'graphql-introspection-active',
  'graphql-batching-abuse',
  'graphql-alias-overload',
  'graphql-introspection-disabled-bypass',
  'graphql-field-suggestion-leak',
  'graphql-fragment-bomb',
  'graphql-schema-driven-attack',
  'mass-assignment',
  'api-versioning-mismatch',
  'idor-numeric',
  'idor-uuid-predictable',
  // CVE / named families
  'shell-shock',
  'log4-shell',
  'spring4-shell',
  'text4-shell',
  'httpoxy',
  'cloud-metadata-attack',
  'env-file-exposure',
  'source-code-disclosure-git',
  // Existing check IDs (from proxyEngine)
  'security-headers',
  'cors-origin',
  'cache-key',
  'method-options',
  'authz-diff',
  'jwt-claims',
  'graphql-introspection',
  'oast-ssrf',
  'reflected-xss',
  'sql-injection-legacy',
  'path-traversal',
  'open-redirect-legacy',
  'command-injection-legacy',
] as const;

export type NewActiveScanCheckId = (typeof ACTIVE_SCAN_CHECK_IDS)[number];

export const CHECK_ID_LABELS: Record<string, string> = {
  'sql-injection': 'SQL injection',
  'xss-reflected': 'Reflected XSS',
  'xss-oracle': 'XSS oracle probe',
  'ssti': 'Server-side template injection',
  'ssti-blind-time': 'SSTI blind timing',
  'lfi-traversal': 'LFI / path traversal',
  'command-injection': 'Command injection',
  'command-injection-blind-time': 'Command injection blind timing',
  'command-injection-blind-oast': 'Command injection blind OAST',
  'ssrf': 'SSRF',
  'ssrf-oast': 'SSRF OAST-confirmed',
  'open-redirect': 'Open redirect',
  'xxe-file': 'XXE file read',
  'xxe-oast': 'XXE OAST-confirmed',
  'nosql-injection': 'NoSQL injection',
  'xpath-injection': 'XPath injection',
  'ldap-injection': 'LDAP injection',
  'expression-language-injection': 'EL injection',
  'csv-formula-injection': 'CSV formula injection',
  'jwt-none-algorithm': 'JWT none algorithm',
  'jwt-weak-secret': 'JWT weak secret',
  'jwt-key-confusion': 'JWT key confusion (RS→HS)',
  'session-fixation': 'Session fixation',
  'csrf-heuristic': 'CSRF heuristic',
  'clickjacking': 'Clickjacking',
  'host-header-injection': 'Host header injection',
  'crlf-header-injection': 'CRLF header injection',
  'password-reset-token-leak': 'Password reset token leak',
  'request-smuggling-cl-te': 'Request smuggling CL.TE',
  'request-smuggling-te-cl': 'Request smuggling TE.CL',
  'request-smuggling-te-te': 'Request smuggling TE.TE',
  'cache-poisoning-unkeyed-header': 'Cache poisoning (unkeyed header)',
  'cache-poisoning-unkeyed-port': 'Cache poisoning (unkeyed port)',
  'cache-deception': 'Cache deception',
  'web-cache-key-discrepancy': 'Web cache key discrepancy',
  'deserialization-java': 'Java deserialization',
  'deserialization-php': 'PHP deserialization',
  'deserialization-dotnet': '.NET deserialization',
  'deserialization-python': 'Python deserialization',
  'deserialization-ruby': 'Ruby deserialization',
  'dom-xss': 'DOM XSS',
  'dom-clobbering': 'DOM clobbering',
  'prototype-pollution-client': 'Prototype pollution (client)',
  'prototype-pollution-server': 'Prototype pollution (server)',
  'postmessage-misconfig': 'postMessage misconfiguration',
  'cors-misconfig-credentialed': 'CORS credentialed misconfiguration',
  'graphql-introspection-active': 'GraphQL introspection (active)',
  'graphql-batching-abuse': 'GraphQL batching abuse',
  'graphql-alias-overload': 'GraphQL alias overload',
  'graphql-introspection-disabled-bypass': 'GraphQL introspection bypass',
  'graphql-field-suggestion-leak': 'GraphQL field suggestion leak',
  'graphql-fragment-bomb': 'GraphQL fragment bomb',
  'graphql-schema-driven-attack': 'GraphQL schema-driven attack',
  'mass-assignment': 'Mass assignment',
  'api-versioning-mismatch': 'API versioning mismatch',
  'idor-numeric': 'IDOR (numeric ID)',
  'idor-uuid-predictable': 'IDOR (predictable UUID)',
  'shell-shock': 'ShellShock (CVE-2014-6271)',
  'log4-shell': 'Log4Shell (CVE-2021-44228)',
  'spring4-shell': 'Spring4Shell (CVE-2022-22965)',
  'text4-shell': 'Text4Shell (CVE-2022-42889)',
  'httpoxy': 'HTTPoxy',
  'cloud-metadata-attack': 'Cloud metadata SSRF',
  'env-file-exposure': '.env file exposure',
  'source-code-disclosure-git': 'Git source code disclosure',
  'security-headers': 'Security headers',
  'cors-origin': 'CORS origin',
  'cache-key': 'Cache key',
  'method-options': 'OPTIONS methods',
  'authz-diff': 'Authenticated-state comparison',
  'jwt-claims': 'JWT claim review',
  'graphql-introspection': 'GraphQL introspection',
  'oast-ssrf': 'OAST SSRF callback',
  'reflected-xss': 'Reflected XSS (legacy)',
  'sql-injection-legacy': 'SQL injection (legacy)',
  'path-traversal': 'Path traversal (legacy)',
  'open-redirect-legacy': 'Open redirect (legacy)',
  'command-injection-legacy': 'Command injection (legacy)',
};
