import type { AiProvider, AutomationRun, ExploitTemplate, HttpExchange, Issue, ToolDefinition } from './types';

export const tools: ToolDefinition[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    shortLabel: 'Dash',
    description: 'Project health, scope, audit queue, and risk movement.',
    status: 'foundation',
    category: 'core',
    count: 7,
  },
  {
    id: 'target',
    label: 'Target Map',
    shortLabel: 'Target',
    description: 'Scope model, host inventory, route tree, and content discovery.',
    status: 'foundation',
    category: 'core',
    count: 18,
  },
  {
    id: 'proxy',
    label: 'Proxy',
    shortLabel: 'Proxy',
    description: 'HTTP history, interception, match rules, and listener control.',
    status: 'ready',
    category: 'core',
    count: 43,
  },
  {
    id: 'repeater',
    label: 'Repeater',
    shortLabel: 'Repeat',
    description: 'Manual request mutation, replay, and response comparison.',
    status: 'foundation',
    category: 'attack',
    count: 4,
  },
  {
    id: 'intruder',
    label: 'Intruder',
    shortLabel: 'Intrude',
    description: 'Payload positions, generators, throttled attack runs, and grep rules.',
    status: 'foundation',
    category: 'attack',
    count: 2,
  },
  {
    id: 'scanner',
    label: 'Scanner',
    shortLabel: 'Scan',
    description: 'Passive and active audits, issue triage, remediation, and evidence.',
    status: 'foundation',
    category: 'attack',
    count: 12,
  },
  {
    id: 'exploit',
    label: 'Exploit Lab',
    shortLabel: 'Exploit',
    description: 'PoC validation, exploit chains, payload lab, and authorization gates.',
    status: 'foundation',
    category: 'attack',
    count: 6,
  },
  {
    id: 'automations',
    label: 'Automations',
    shortLabel: 'Auto',
    description: 'Scheduled workflows, macros, crawl/audit runners, and CI jobs.',
    status: 'foundation',
    category: 'platform',
    count: 8,
  },
  {
    id: 'ai',
    label: 'AI Agents',
    shortLabel: 'AI',
    description: 'Claude/Codex-assisted triage, replay planning, exploit analysis, and reports.',
    status: 'foundation',
    category: 'platform',
    count: 3,
  },
  {
    id: 'logger',
    label: 'Logger',
    shortLabel: 'Log',
    description: 'All tool-generated HTTP traffic, filters, and tool handoffs.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'organizer',
    label: 'Organizer',
    shortLabel: 'Org',
    description: 'Curated message collections, annotations, workflow status, and CSV/share export.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'search',
    label: 'Search',
    shortLabel: 'Search',
    description: 'Full-text, structured, semantic, and evidence-aware project search.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'viewer',
    label: 'Viewer',
    shortLabel: 'View',
    description: 'HTML, JSON, image, binary, websocket, GraphQL, JWT, and diff viewers.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'sequencer',
    label: 'Sequencer',
    shortLabel: 'Seq',
    description: 'Token entropy sampling, bit-level tests, and predictability reports.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'decoder',
    label: 'Decoder',
    shortLabel: 'Decode',
    description: 'Encoding, hashing, canonicalization, and transform chains.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'comparer',
    label: 'Comparer',
    shortLabel: 'Compare',
    description: 'Side-by-side request, response, and binary body diffing.',
    status: 'foundation',
    category: 'analysis',
  },
  {
    id: 'collaborator',
    label: 'Callbacks',
    shortLabel: 'Calls',
    description: 'Out-of-band interaction tracking and payload correlation.',
    status: 'foundation',
    category: 'platform',
    count: 3,
  },
  {
    id: 'extensions',
    label: 'Extensions',
    shortLabel: 'Ext',
    description: 'Plugin catalog, local extensions, APIs, and sandbox permissions.',
    status: 'foundation',
    category: 'platform',
  },
  {
    id: 'reports',
    label: 'Reports',
    shortLabel: 'Report',
    description: 'Technical findings, executive summaries, and export pipelines.',
    status: 'foundation',
    category: 'platform',
    count: 5,
  },
  {
    id: 'settings',
    label: 'Settings',
    shortLabel: 'Config',
    description: 'Listeners, certificates, project safety, updates, and packaging.',
    status: 'foundation',
    category: 'platform',
  },
];

export const seedExchanges: HttpExchange[] = [
  {
    id: 'hx-1031',
    method: 'GET',
    host: 'app.shop.local',
    path: '/api/account/profile',
    url: 'https://app.shop.local/api/account/profile',
    status: 200,
    length: 1842,
    mime: 'application/json',
    risk: 'medium',
    timing: 128,
    notes: 'Session object exposes role hints',
    source: 'proxy',
    time: '13:18:42',
    tags: ['in-scope', 'auth'],
    requestRaw:
      'GET /api/account/profile HTTP/2\nHost: app.shop.local\nCookie: session=eyJhbGciOi...\nAccept: application/json\nX-Requested-With: ProxyForge\n\n',
    responseRaw:
      'HTTP/2 200 OK\nContent-Type: application/json\nCache-Control: no-store\n\n{\n  "id": "usr_1842",\n  "email": "analyst@example.local",\n  "role": "support_admin",\n  "featureFlags": ["refunds", "exports"]\n}',
  },
  {
    id: 'hx-1032',
    method: 'POST',
    host: 'app.shop.local',
    path: '/api/refunds',
    url: 'https://app.shop.local/api/refunds',
    status: 403,
    length: 612,
    mime: 'application/json',
    risk: 'high',
    timing: 231,
    notes: 'Authorization boundary candidate',
    source: 'repeater',
    time: '13:19:07',
    tags: ['authz', 'candidate'],
    requestRaw:
      'POST /api/refunds HTTP/2\nHost: app.shop.local\nContent-Type: application/json\nAuthorization: Bearer eyJ...\n\n{\n  "orderId": "ord_90210",\n  "amount": 7900,\n  "reason": "manual review"\n}',
    responseRaw:
      'HTTP/2 403 Forbidden\nContent-Type: application/json\n\n{\n  "error": "missing_permission",\n  "required": "refunds.write"\n}',
  },
  {
    id: 'hx-1033',
    method: 'GET',
    host: 'cdn.shop.local',
    path: '/assets/app.8e31.js',
    url: 'https://cdn.shop.local/assets/app.8e31.js',
    status: 200,
    length: 90122,
    mime: 'application/javascript',
    risk: 'low',
    timing: 84,
    notes: 'Static bundle contains internal route names',
    source: 'proxy',
    time: '13:20:31',
    tags: ['static'],
    requestRaw:
      'GET /assets/app.8e31.js HTTP/2\nHost: cdn.shop.local\nAccept: */*\n\n',
    responseRaw:
      'HTTP/2 200 OK\nContent-Type: application/javascript\n\nconst routes=["/admin/orders","/admin/refunds","/internal/export"];',
  },
  {
    id: 'hx-1034',
    method: 'OPTIONS',
    host: 'api.shop.local',
    path: '/v2/graphql',
    url: 'https://api.shop.local/v2/graphql',
    status: 204,
    length: 0,
    mime: 'text/plain',
    risk: 'info',
    timing: 42,
    notes: 'CORS policy allows expected origin',
    source: 'scanner',
    time: '13:21:04',
    tags: ['cors', 'passive'],
    requestRaw:
      'OPTIONS /v2/graphql HTTP/2\nHost: api.shop.local\nOrigin: https://app.shop.local\nAccess-Control-Request-Method: POST\n\n',
    responseRaw:
      'HTTP/2 204 No Content\nAccess-Control-Allow-Origin: https://app.shop.local\nAccess-Control-Allow-Credentials: true\n\n',
  },
  {
    id: 'hx-1035',
    method: 'CONNECT',
    host: 'auth.shop.local:443',
    path: 'auth.shop.local:443',
    url: 'https://auth.shop.local',
    status: 200,
    length: 0,
    mime: 'tunnel',
    risk: 'info',
    timing: 19,
    notes: 'Tunnel metadata only until HTTPS MITM certificate is enabled',
    source: 'proxy',
    time: '13:21:22',
    tags: ['tunnel'],
    requestRaw: 'CONNECT auth.shop.local:443 HTTP/1.1\nHost: auth.shop.local:443\n\n',
    responseRaw: 'HTTP/1.1 200 Connection Established\n\n',
  },
];

export const seedIssues: Issue[] = [
  {
    id: 'iss-1',
    title: 'Role hint exposed in profile response',
    severity: 'medium',
    host: 'app.shop.local',
    path: '/api/account/profile',
    confidence: 'firm',
    status: 'open',
    detail: 'Authenticated profile responses expose internal role names and feature flags that help map privileged workflow boundaries.',
    remediation: 'Return only user-facing authorization state and move internal role labels behind server-side checks.',
  },
  {
    id: 'iss-2',
    title: 'Administrative route names present in public bundle',
    severity: 'low',
    host: 'cdn.shop.local',
    path: '/assets/app.8e31.js',
    confidence: 'firm',
    status: 'triaged',
    detail: 'Public JavaScript includes route names for administrative workflows. This is not a vulnerability by itself but improves attack planning.',
    remediation: 'Assume route names are public and enforce authorization server-side on every administrative endpoint.',
  },
  {
    id: 'iss-3',
    title: 'Callback payload interaction observed',
    severity: 'high',
    host: 'api.shop.local',
    path: '/v2/graphql',
    confidence: 'tentative',
    status: 'open',
    detail: 'A collaborator-style token received an out-of-band DNS lookup after a queued import request.',
    remediation: 'Review outbound fetch paths, disable arbitrary URL fetching, and enforce allowlists on import processors.',
  },
];

export const automations: AutomationRun[] = [
  {
    id: 'auto-1',
    name: 'Authenticated crawl and passive audit',
    status: 'running',
    trigger: 'Manual launch',
    scope: '*.shop.local',
    lastRun: '13:17:04',
    steps: ['Use saved browser profile', 'Crawl scoped routes', 'Record HTTP history', 'Run passive checks', 'Open report deltas'],
  },
  {
    id: 'auto-2',
    name: 'Replay authz matrix',
    status: 'ready',
    trigger: 'On request tagged authz',
    scope: 'app.shop.local/api/*',
    lastRun: '12:41:29',
    steps: ['Clone selected request', 'Swap role tokens', 'Replay at 1 rps', 'Compare status/body deltas', 'Create evidence bundle'],
  },
  {
    id: 'auto-3',
    name: 'Callback monitor enrichment',
    status: 'complete',
    trigger: 'Every 5 minutes',
    scope: 'callback tokens',
    lastRun: '13:22:00',
    steps: ['Poll interactions', 'Correlate payload ids', 'Score SSRF/OAST hints', 'Attach DNS/HTTP evidence'],
  },
  {
    id: 'auto-4',
    name: 'Exploit chain dry run',
    status: 'blocked',
    trigger: 'Approval required',
    scope: 'Explicit targets only',
    lastRun: 'Not run',
    steps: ['Validate preconditions', 'Check scope and rate limits', 'Run non-destructive PoC', 'Capture proof', 'Stop on state change'],
  },
];

export const aiProviders: AiProvider[] = [
  {
    id: 'codex',
    label: 'Codex',
    status: 'configured',
    model: 'local connector',
    purpose: 'Code-aware replay plans, extension authoring, and evidence normalization.',
  },
  {
    id: 'claude',
    label: 'Claude',
    status: 'needs-key',
    model: 'provider key required',
    purpose: 'Long-context triage, report writing, and exploit hypothesis review.',
  },
  {
    id: 'local',
    label: 'Local Model',
    status: 'offline',
    model: 'OpenAI-compatible endpoint',
    purpose: 'Private payload clustering and semantic search without external calls.',
  },
];

export const exploitTemplates: ExploitTemplate[] = [
  {
    id: 'xp-1',
    title: 'Authorization bypass replay',
    className: 'Access control',
    status: 'ready',
    target: 'POST /api/refunds',
    safety: 'Read-only comparison by default; state-changing replay requires approval.',
    evidence: 'Compares support/admin/customer tokens against status, body, and side effects.',
  },
  {
    id: 'xp-2',
    title: 'SSRF callback validation',
    className: 'Server-side request forgery',
    status: 'requires-approval',
    target: '/v2/imports',
    safety: 'Uses unique callback token and stops after first DNS/HTTP interaction.',
    evidence: 'Correlates OAST token, timestamp, source address, and import request.',
  },
  {
    id: 'xp-3',
    title: 'GraphQL introspection and field probe',
    className: 'API exposure',
    status: 'draft',
    target: '/v2/graphql',
    safety: 'Low-rate metadata probes only; mutation execution disabled by default.',
    evidence: 'Captures schema visibility, hidden fields, and authorization deltas.',
  },
  {
    id: 'xp-4',
    title: 'JWT confusion preflight',
    className: 'Token validation',
    status: 'ready',
    target: 'Authorization headers',
    safety: 'Offline token mutation and verification unless a scoped replay is approved.',
    evidence: 'Records accepted algorithms, key ids, claims, and replay outcomes.',
  },
];

export const siteMap = [
  {
    host: 'app.shop.local',
    nodes: ['/login', '/dashboard', '/api/account/profile', '/api/refunds', '/admin/orders'],
  },
  {
    host: 'api.shop.local',
    nodes: ['/v2/graphql', '/v2/imports', '/v2/webhooks', '/health'],
  },
  {
    host: 'cdn.shop.local',
    nodes: ['/assets/app.8e31.js', '/assets/vendor.19af.js', '/favicon.ico'],
  },
];
